### ISSUE TITLE
Nothing happens when locking/unlocking

### ISSUE THREAD

**Issue by jesus2099** [stuerp/foo_lock#1]
It does not pause or stop when I lock, despite foo_lock settings (in Advanced).
foobar2000 console logs nothing special, either.
Is **foo_lock** still supposed to work?

Maybe it's because I have installed foobar2000 with the "per user" install option (I have no admin rights)?
Maybe I should install latest foobar2000 (2.1.5)?

```
64-bit Windows 10 Entreprise 22H2
foobar2000 v2.0 [x64]
foo_lock 0.8.1.0
```

**Comment by stuerp** [comment]
It worked when I released it, for sure. I don't really use it myself. It was a forum request. I'll do some checking. Maybe Microsoft 'fixed' something that broke the functionality. 2.1.5 is not required; neither is admin.

**Comment by stuerp** [comment]
After specifying the lock and unlock action you have to enable or disable it with the "Playback / Pause on lock" menu item. I'll update the README.

Can you confirm that it works as released when you do that? It still does on my configuration.

**Comment by jesus2099** [comment]
Wow!! Ii seems I forgot that!
Thanks so much!
